image: python:3.8
stages:
  - test
  - build

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

lint:
  stage: test
  script:
  - pip install restructuredtext_lint
  - rst-lint source

preview:
  stage: build
  script:
  - pip install -r requirements.txt
  - make html
  - mv build/html public
  - echo "Preview this build at ${CI_PAGES_URL/${CI_PAGES_DOMAIN}\//${CI_PAGES_DOMAIN}\/-\/}/-/jobs/${CI_JOB_ID}/artifacts/public/index.html"
  except:
  - master
  artifacts:
    paths:
    - public

pages:
  stage: build
  script:
  - pip install -r requirements.txt
  - make html
  - mv build/html public
  artifacts:
    paths:
    # this name is fixed/required for automatic GitLab Pages deployment
    - public
  only:
  - master
