name: Infrastructure

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest
    env:
      working-directory: ./infrastructure

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cfn-lint
    - name: Lint with cfn-lint
      working-directory: ${{ env.working-directory }}
      run: |
        cfn-lint -I templates/*.yaml
