name: Warehouse Loader Checks

on: [push]

jobs:
  warehouse-loader:

    runs-on: ubuntu-latest
    env:
      working-directory: ./warehouse-loader

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: "Python version"
      run: python -V

    - name: Install dependencies
      working-directory: ${{ env.working-directory }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Lint with black
      working-directory: ${{ env.working-directory }}
      run: |
        black . --check

    - name: Lint with flake8
      working-directory: ${{ env.working-directory }}
      run: |
        flake8 . --count --show-source --statistics

    - name: Run tests
      working-directory: ${{ env.working-directory }}
      run: |
        pytest
